name: Build and Release Steve API

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: macos-10.15
          artifact_name: steve
          asset_name: steve-macos-amd64
        - os: windows-2019
          artifact_name: steve.exe
          asset_name: steve-windows-amd64
        - os: ubuntu-latest
          artifact_name: steve
          asset_name: steve-linux-amd64
    runs-on: ${{ matrix.os }}
    steps: 
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive
        persist-credentials: false
    
    - name: Build Steve API
      run: |
        cd src/steve
        go build
    
    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ./src/steve/${{ matrix.artifact_name }}
        if-no-files-found: error

    - name: Upload Assets
      uses: SierraSoftworks/gh-releases@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: 'false'
        files: |
          - ./src/steve/${{ matrix.artifact_name }}
    